eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
    
zuul:
   routes: 
      say-hello-service2: #这个可以随便写只是一个名字 
         path: /say-hello-service1/** #这个是请求地址，地址栏要的就是这请求的路径
         serviceId: SERVICE-SAY-HELLO #这是这个路径需要打到的服务  然后找到路径下/**的方法进行调用
      greeting-service:
         path: /greeting-service/**
         serviceId: GREETING-SERVICE